### ISSUE TITLE
Error when importing with numpy >= 1.25

### ISSUE THREAD

**Issue by hmcezar** [rainwoodman/pfft-python#10]
Numpy 1.25 [removed nose testing support](https://github.com/numpy/numpy/pull/23041) and importing pfft-python results in

```
ImportError: cannot import name 'Tester' from 'numpy.testing'
```

**Comment by rainwoodman** [comment]
Do you have a stack trace of the error message?

**Comment by hmcezar** [comment]
Sure!

In an empty conda environment I installed the pfft dependencies (make sure to force "cython<3"):
```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
binutils_linux-64         2.40                 hbdbef99_2    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.08.22           h06a4308_0  
cython                    0.29.36                  pypi_0    pypi
gcc                       12.3.0               h8d2909c_2    conda-forge
gcc_impl_linux-64         12.3.0               he2b93b0_2    conda-forge
gcc_linux-64              12.3.0               h76fc315_2    conda-forge
gfortran                  12.3.0               h499e0f7_2    conda-forge
gfortran_impl_linux-64    12.3.0               hfcedea8_2    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
intel-openmp              2023.1.0         hdb19cb5_46305  
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0  
libgcc-devel_linux-64     12.3.0               h8bca6fd_2    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libnsl                    2.0.0                hd590300_1    conda-forge
libsanitizer              12.3.0               h0f45ef3_2    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.11.5               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mkl                       2023.1.0         h213fc3f_46343  
mkl-service               2.4.0           py311h5eee18b_1  
mkl_fft                   1.3.8           py311h5eee18b_0  
mkl_random                1.2.4           py311hdb19cb5_0  
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.1.4           py311h4267d7f_1    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     1.26.0          py311h08b1b3b_0  
numpy-base                1.26.0          py311hf175353_0  
openmpi                   4.1.6              hc5af2df_101    conda-forge
openmpi-mpicc             4.1.6              hd590300_101    conda-forge
openssl                   3.1.3                hd590300_0    conda-forge
pfft-python               0.1.20                   pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python_abi                3.11                    4_cp311    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
sqlite                    3.43.0               h2c6b66d_0    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tbb                       2021.10.0            h00ab1b0_1    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.4.2                h5eee18b_0  
zlib                      1.2.13               hd590300_5    conda-forge
```

If you run 
```bash
pip install git+https://github.com/rainwoodman/pfft-python.git
```

And then open a `python` console and type `import pfft` you get:
```python
>>> import pfft
[hmcezar-thinkpad:71417] mca_base_component_repository_open: unable to open mca_btl_openib: librdmacm.so.1: cannot open shared object file: No such file or directory (ignored)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hmcezar/anaconda3/envs/test-pfft-python/lib/python3.11/site-packages/pfft/__init__.py", line 5, in <module>
    from numpy.testing import Tester
ImportError: cannot import name 'Tester' from 'numpy.testing' (/home/hmcezar/anaconda3/envs/test-pfft-python/lib/python3.11/site-packages/numpy/testing/__init__.py)
```

**Comment by rainwoodman** [comment]
Thanks. The stacktrace was illuminating! I think the commit I just pushed should have fixed this issue. Please test and feel free to reopen.

**Comment by hmcezar** [comment]
Just reinstalled the package and at least the import is working. Thanks!

Daring to make a request, when you have the time, could you please make new releases and upload the latest versions of `pmesh`, `pfft-python` and `mpsort`  to PyPI?

**Comment by rainwoodman** [comment]
Sure -- an update is long due, though I suspect most of the automated systems are gone with travis-ci or disabled from github-workflow. Do you have a recommendation on the automation tools, btw?

I'll take a look this weekend.

**Comment by rainwoodman** [comment]
Done. Uploaded new releases of pmehs, pfft-python and mpsort to pypi. FYI: @dstndstn
